<?php // module/Album/view/album/album/index.phtml:

$title = 'Categorías';
$this -> headTitle($title);
?>
<h1><?= $this -> escapeHtml($title); ?></h1>
<p>
	<a href="<?= $this -> url('category', array('action' => 'add')); ?>">Nueva categoría</a>
</p>

<table class="table">
	<tr>
		<th>#</th>
		<th>Nombre</th>
		<th>&nbsp;</th>
	</tr>
	<?php foreach ($categories as $category) : $i++; ?>
	<tr>
		<td><?= $i; ?></td>
		<td><?= $this->escapeHtml($category->code); ?></td>
		<td><?= $this->escapeHtml($category->name); ?></td>
		<td><?= $this->escapeHtml($category->category); ?></td>
		<td>
		    <a href="<?= $this->url('category', array('action' => 'edit', 'id' => $category->id)); ?>">Edit</a>
		    <a href="<?= $this->url('category', array('action' => 'delete', 'id' => $category->id)); ?>">Delete</a>
		</td>
	</tr>
	<?php endforeach; ?>
</table>