<?php
$title = 'Agregar nuevo producto';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title); ?></h1>
<?php 
$form->setAttribute('action', $this->url('product', array('action' => 'add')));
$form->setAttribute('class', 'form-horizontal');

$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('code'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('category'));
echo $this->formSubmit($form->get('submit'));
?>
	<a href="<?= $this -> url('product'); ?>" class="btn btn-danger">Cancelar</a>
<?php
echo $this->form()->closeTag();